### PR TITLE
Added the source file for the web application of raffle calculator for issue #172

### PR DESCRIPTION
**Pull request by zerkben**
I have added the git repo deployed on the web application for the upgrade of raffle calculator on ghst.gg. Essentially the file under the folder utils,  'raffleCalculationImported.py' defines ticket class and respective calculations with regards to binomial distribution. Rest relies on user input by interactive web interface in file, 'main.py', for the dash framework where the instance of ticket class is created for plotting the probabilities.

### CODE REVIEW

**Comment by yanik-ai** [comment]
I don't think we can accept submodules. In the future client will be used to sign transactions, and it will be much-much harder to provide proper security with third party submodules

**Comment by zerkben** [comment]
Okay I will update it accordingly, just the necessary files without repo/git structure which could run on a local server as an example

**Comment by zerkben** [comment]
Got rid of the git structure and other files related to heroku app, the added new folder has only the source code which runs on local server without any problem. Deleted the previous source file folder of the app.

**Comment by yanik-ai** [comment]
Thank you very much for the effort! But I noticed it is python and we this projects is using JS/React, otherwise it will complicate deployment and development. 

(1) You'r code is still reusable, we can migrate the core/formula to JS! 
(2) if you interested in python/django we have this stack for a client backend in prototype stage

**Comment by dudendy** [comment]
moving to archive

**Pull request closed without merging**
