### PR TITLE
Update guild.js with new MSGgaang data

### PR DESCRIPTION
**Pull request by chair28980**
Updated MSG gaang data

### CODE REVIEW

**Review by dudendy — CHANGES_REQUESTED** [review]
@chair28980 thanks for your contribution!

To be able to display your guild you need to put each member address into single brackets:

**Wrong**
```
members: [
    0xc13eC844Eb19D6A72DDD5F2779484BA35279A817,
    0x86aecfc1E3973108Ce14b9b741a99d3466127170,
]
```

**Correct**
```
members: [
    '0xc13eC844Eb19D6A72DDD5F2779484BA35279A817',
    '0x86aecfc1E3973108Ce14b9b741a99d3466127170',
]
```

Also if you would like to us image that you add as a banner (which is pretty awesome IMHO) you need to put image path in the `banner` section:
Change this `banner: '',` to this `banner: require('../assets/images/guilds/msg-gang-banner.jpg').default,`

**Comment by dudendy** [comment]
> @chair28980 thanks for your contribution!
> 
> To be able to display your guild you need to put each member address into single brackets:
> 
> **Wrong**
> 
> ```
> members: [
>     0xc13eC844Eb19D6A72DDD5F2779484BA35279A817,
>     0x86aecfc1E3973108Ce14b9b741a99d3466127170,
> ]
> ```
> 
> **Correct**
> 
> ```
> members: [
>     '0xc13eC844Eb19D6A72DDD5F2779484BA35279A817',
>     '0x86aecfc1E3973108Ce14b9b741a99d3466127170',
> ]
> ```
> 
> Also if you would like to us image that you add as a banner (which is pretty awesome IMHO) you need to put image path in the `banner` section: Change this `banner: '',` to this `banner: require('../assets/images/guilds/msg-gang-banner.jpg').default,`

@chair28980 nevermind, I made this changes

**Review by dudendy — APPROVED** [review]

**Comment by chair28980** [comment]
@dudendy apologies for the mis formatting sir! Thank you for correcting.

https://media.giphy.com/media/xUOxf1AluChkt3CtQk/giphy.gif

**Pull request merged**
